# Generated by Django 4.1.3 on 2022-11-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_vagas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vagas',
        ),
    ]
