# Generated by Django 4.1.3 on 2022-11-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_vagas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nicho_mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicho', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nicho_mercado',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.ManyToManyField(to='empresa.nicho_mercado'),
        ),
    ]
