# Generated by Django 4.1.3 on 2022-11-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_remove_empresa_nicho_mercado_empresa_nicho_mercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nicho_mercado', to='empresa.nicho_mercado'),
        ),
    ]
