# Generated by Django 4.1.3 on 2022-11-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_remove_empresa_nicho_mercado_empresa_nicho_mercado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nicho_mercado',
        ),
        migrations.AddField(
            model_name='nicho_mercado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa'),
            preserve_default=False,
        ),
    ]
